### PR TITLE
Use uncontrolled components

### PR DESCRIPTION
**Pull request by frontsideair**
This will avoid the complexity of hooks and make the example much more similar to a vanilla example.

### CODE REVIEW

**Comment by Martinsos** [comment]
@frontsideair Thank you for the suggestion!
This looks great, but when I tried doing running this code, I got following error: `Error: event.currentTarget.reset is not a function`.
It seems that when using React, events are somewhat modified and resetting it in this fashion is not an option anymore https://stackoverflow.com/questions/54083068/unable-to-reset-form-input-fields-react-js-controlled-component?

**Comment by frontsideair** [comment]
Ah, sorry for not actually testing it. The problem is indeed about event pooling that React does and after the await the synthetic event is returned to the pool. I have a fix and have [tested it](https://codesandbox.io/s/falling-fire-inn0j?file=/src/App.tsx) to see if it actually works.

**Comment by Martinsos** [comment]
Thanks @frontsideair! What worries me here is that most people will not know about this, and will therefore not understand why these few lines of code are written like this -> they might modify them / shorten them / change the order and suddenly code will stop working. What do you think? Maybe this is just not the "React way", although "React way" is not the nicest also.

I am actually confused that this works -> I believe you that it does, but I am having hard time figuring out why - the change you made is that you stored description into a variable, then called reset, and then called await -> how does that help?

**Comment by frontsideair** [comment]
I understand what you mean. When I opened the PR I though it would be more straightforward to use uncontrolled components as they work more like vanilla JS, but I agree the React event system makes it more confusing. If people move things around and break it then they need some advanced knowledge to understand what went wrong.

The problem is that React uses event pooling and the events are returned to the pool at the next event loop tick. Using an `await` causes the event to be returned to the pool, so we need to store the input value while we still have access to the event.

On the other hand, React 17 [doesn't use event pooling anymore](https://reactjs.org/docs/legacy-event-pooling.html) so it shouldn't break now. I'll test this.

**Comment by frontsideair** [comment]
Looks like I was already using React 17 in [my example](https://codesandbox.io/s/falling-fire-inn0j?file=/src/App.tsx) so I was confused why the problem was still happening. Looks like changing `currentTarget` to `target` fixes this gotcha and it had nothing to do with event pooling. (You can recreate the event bubbling related problem by downgrading the React version in the sandbox.)

I don't fully understand why `currentTarget` was set to null on the next event tick but switching to `target` makes it more beginner-proof. I can update the PR if you also agree.

Edit: I learned [why this is happening](https://github.com/facebook/react/issues/2857#issuecomment-70006324) and it's consistent. I defensively use `currentTarget` over `target` to get better type safety  with TypeScript but looks like in this case it's making matters confusing.

Also found related [MDN article](https://developer.mozilla.org/en-US/docs/Web/API/Event/currentTarget), see the note. Interesting that I didn't notice this before.

**Comment by Martinsos** [comment]
@frontsideair I understand, thanks for this detailed research, I just learned something :)!
Sounds good, if you can replace currentTarget with target, and maybe skip having additional variable which is not needed any more, I think we are good! This will also require changes in the actual example, not just in the docs, but that needs to be done in the other repo -> I can take care of that.

**Comment by frontsideair** [comment]
Done, happy that I also learned something. :)

**Comment by Martinsos** [comment]
Awesome! I updated the code in TodoApp example in the main repo https://github.com/wasp-lang/wasp/commit/f0c728dfbb9dd97cb9db8196f4f424fd9ccb3922 and also did a final touch here in this PR, I will merge it now! Thanks for help with this.

**Pull request merged**
